# netlify.toml
[build]
  # Directory where your Angular app is located after building
  base = "frontend"

  # Command to build your Angular app
  command = "ng build"
 

  # Publish directory for Netlify
  publish = "dist/quotes_keeper_2"
  
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
