# netlify.toml
[build]
  # Directory where your Angular app is located after building
  base = "frontend"

  # Command to build your Angular app
  command = "npm install --legacy-peer-deps && npm run build:prod"
 

  # Publish directory for Netlify
  publish = "dist/quotes_keeper_2"
