name: run cypress
on: 
  workflow_dispatch: # Allow you to run it manually from github

jobs:
  clone_repo_add_cypress_data:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout # clone the repository into the runner environment
        uses: actions/checkout@v4
      
      - name: Install Dependecies
        run: |
          cd testing
          npm install --legacy-peer-deps
        shell: bash

      - name: run Cypress 
        run: |
          cd testing
          npx cypress run
        shell: bash